version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/app
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"