module.exports = {
	TYPE_INBOUND: 'TYPE_INBOUND',

    TYPE_OUTBOUND_HT_REPORT_1: 'TYPE_OUTBOUND_HT_REPORT_1',
	TYPE_OUTBOUND_HT_REPORT_2: 'TYPE_OUTBOUND_HT_REPORT_2',
	TYPE_OUTBOUND_HT_REPORT_3: 'TYPE_OUTBOUND_HT_REPORT_3',
	TYPE_OUTBOUND_HT_REPORT_COMPLETE: 'TYPE_OUTBOUND_HT_REPORT_COMPLETE',
	TYPE_OUTBOUND_HT_REPORT_10: 'TYPE_OUTBOUND_HT_REPORT_10',

    TYPE_NONE: 'TYPE_NONE',
	TYPE_MEMBER_NOT_FOUND: 'TYPE_MEMBER_NOT_FOUND',

    REPORT_FAMILY_NEEDS: 'REPORT_FAMILY_NEEDS',
    REPORT_VISITED_FAMILIES: 'REPORT_VISITED_FAMILIES',
    REPORT_VISITED: 'REPORT_VISITED',
    REPORT_CHALLENGES: 'REPORT_CHALLENGES',

	TYPE_ANY: undefined
};
