module.exports = {
	TYPE_INBOUND: "TYPE_INBOUND",
	TYPE_OUTBOUND_HT_REPORT_1: "TYPE_OUTBOUND_HT_REPORT_1",
	TYPE_OUTBOUND_HT_REPORT_2: "TYPE_OUTBOUND_HT_REPORT_2",
	TYPE_OUTBOUND_HT_REPORT_COMPLETE: "TYPE_OUTBOUND_HT_REPORT_COMPLETE",
	TYPE_NONE: "TYPE_NONE",
	TYPE_MEMBER_NOT_FOUND: "TYPE_MEMBER_NOT_FOUND",
	TYPE_ANY: undefined
};
